kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # allow the local host to make requests to ingress controller over ports 80/443
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # - hostPort: 30000
  #   containerPort: 30000
  #   listenAddress: "127.0.0.1"

