services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  myapp:
    image: golang
    working_dir: /go/src
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/go/src
    command: ["tail", "-f", "/dev/null"]
